In [1]:
import numpy as np

### Create an array from an iterable
Such as
- ```list```
- ```tuple```
- ```range``` iterator

Notice that not all iterables can be used to create a numpy array, such as ```set``` and ```dict```

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Create an array with specified data type

In [5]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)
print('Data Type: ' + str(arr.dtype))

[[1 2 3]
 [4 5 6]]
Data Type: int16


### Create an aray within specified range
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [6]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


### Create an array of evenly spaced numbers within specified range
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [7]:
arr, step_size = np.linspace(0, 5, 8, endpoint=False, retstep=True)
print(arr)
print('The step size is ' + str(step_size))

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
The step size is 0.625


### Create an array of random values of given shape
```np.random.rand()``` method returns values in the range [0,1)

In [8]:
arr = np.random.rand(3, 3)
print(arr)

[[0.06347901 0.84146073 0.82871538]
 [0.50760868 0.50914515 0.9301876 ]
 [0.98328975 0.22805972 0.78315838]]


### Create an array of zeros of given shape 
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [9]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
zeros = np.zeros_like(arr)
print(zeros)
print('Data Type: ' + str(zeros.dtype))

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64


### Create an array of ones of given shape 
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [11]:
ones = np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

[[1 1 1]
 [1 1 1]]
Data Type: int32


### Create an empty array of given shape 
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [13]:
empty = np.empty((5,5))
print(empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56602523e-307
  1.33511018e-306]
 [7.56599807e-307 8.90104239e-307 1.89146896e-307 1.37961302e-306
  6.23053614e-307]
 [6.23053954e-307 9.34609790e-307 8.45593934e-307 9.34600963e-307
  1.86921143e-306]
 [6.23061763e-307 8.90104239e-307 6.89804132e-307 1.22387465e-307
  1.42418172e-306]
 [2.04712906e-306 7.56589622e-307 1.11258277e-307 8.90111708e-307
  0.00000000e+000]]


In [14]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
empty = np.empty_like(arr)
print(empty)
print('Data Type: ' + str(empty.dtype))

[[1065353216 1073741824 1077936128]
 [1082130432 1084227584 1086324736]]
Data Type: int64


### Create an array of constant values of given shape  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [15]:
full = np.full((4,4), 5)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

[[5. 5.]
 [5. 5.]]
Data Type: float64


### Create an array in a repetitive manner
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```np.tile()```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [19]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 2)) 

[0 0 1 1 2 2 3 3 4 4 5 5]


In [20]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) 

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [21]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))    

[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]]


In [22]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [23]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


### Create an identity matrix of given size
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [24]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=-1)
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [26]:
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Create an array with given values on the diagonal

In [27]:
arr = np.random.rand(5,5)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.60628263 0.12259387 0.07977116 0.104798   0.14692582]
 [0.26260367 0.50521548 0.82194249 0.88366821 0.21038444]
 [0.77110004 0.12902761 0.63049478 0.66293369 0.50503216]
 [0.36120752 0.88019742 0.14912464 0.59092513 0.48803531]
 [0.97207721 0.0254087  0.47572183 0.22194431 0.49097873]]
Values on the diagonal: [0.60628263 0.50521548 0.63049478 0.59092513 0.49097873]


In [28]:
# Not necessarily to be a square matrix
arr = np.random.rand(10,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

[[0.17384495 0.76631465 0.28421076]
 [0.10336524 0.2151758  0.43196162]
 [0.46877293 0.10235019 0.38029731]
 [0.3824711  0.17925864 0.52196928]
 [0.16932479 0.39755675 0.17697451]
 [0.96896029 0.17597832 0.27660977]
 [0.43460303 0.53126587 0.66799194]
 [0.56053028 0.44099747 0.71457736]
 [0.33679485 0.34289369 0.32918158]
 [0.19788396 0.60242331 0.33236605]]
Values on the diagonal: [0.17384495 0.2151758  0.38029731]


In [29]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Sampling

In [34]:
#RandomState exposes a number of methods for generating random numbers drawn from a variety of probability distributions.
rs = np.random.RandomState(111)
rs.rand(10)

array([0.61217018, 0.16906975, 0.43605902, 0.76926247, 0.2953253 ,
       0.14916296, 0.02247832, 0.42022449, 0.23868214, 0.33765619])

In [35]:
np.random.uniform(0, 10, 5)

array([1.40518167, 8.01343148, 9.7533868 , 6.98292152, 5.20905498])

#### generating a random sample

In [36]:
# generate a random scalar
print(np.random.rand()) 

0.863587444201141


In [37]:
# generate a 1-D array
print(np.random.rand(3))           

[0.25709875 0.5330886  0.62011658]


In [38]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.12534114 0.3844781  0.23877356]
 [0.50032398 0.47863599 0.09924271]
 [0.36579523 0.83914911 0.57690048]]


### generating a sample from the standard normal distribution (mean = 0, var = 1)
 * Randn function Returns a sample (or samples) from the “standard normal” distribution.

In [42]:
print(np.random.randn(3,3))

[[-1.11016425 -0.81558633 -0.29094132]
 [-0.48499756 -1.74461338 -1.15601097]
 [-1.15767758  0.16694584 -0.25717236]]


### generate an array of random integers in a given interval [low, high)

In [41]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[9 2 8]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [43]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.25646426 0.06411217 0.4432381  0.84235117 0.86737712 0.87733053
 0.41736243 0.32126227 0.21058723 0.21162004]
[0.99789864 0.70833879 0.40453683 0.49749392 0.13495896 0.38880208
 0.17442791 0.71103116 0.53620191 0.04796724]
[0.09473221 0.5525963  0.37811673 0.15802128 0.23660943 0.18040964
 0.61359686 0.34547221 0.65488718 0.67304858]
[0.71001198 0.15540849 0.16305398 0.47278307 0.82990235 0.83331886
 0.17131671 0.43909243 0.99467048 0.04401107]


### shuffle an array in place

In [44]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
np.random.shuffle(arr)
print(arr)

[5 6 2 0 3 4 9 1 8 7]


### Permutation of an array

In [46]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [0 7 1 5 9 2 4 8 3 6]


## Mathematical Operations


In [48]:
# element-wise addition, subtraction, multiplication and division

print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[10 11 12 13 14 15 16 17 18 19]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [49]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


In [50]:
#Element-wise exponentiation
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [51]:
# natural log
print(np.log(arr)) 

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


<ipython-input-51-3c505debb44f>:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [52]:
# base 2 log
print(np.log2(arr))  

[      -inf 0.         1.         1.5849625  2.         2.32192809
 2.5849625  2.80735492 3.         3.169925  ]


<ipython-input-52-d742b90ad893>:2: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(arr))


In [53]:
# base 10 log
print(np.log10(arr))  

[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251]


<ipython-input-53-f477a238bcbb>:2: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(arr))


In [54]:
#Square root
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [55]:
#Trignometry operations : sin
print(np.sin(arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [56]:
#Trignometry operations : cosine
print(np.cos(arr))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]


In [58]:
#Trignometry operations : Tan
print(np.tan(arr))

[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [59]:
# sum along the row
print(np.sum(arr, axis=0))  

45


In [61]:
arr = np.random.rand(5,5)
# sum along the column
print(np.sum(arr, axis=1))  

[2.85524394 2.85034449 1.97036539 1.567612   2.73592902]


In [62]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.32259571 0.17287446 0.02590609 0.4206482  0.10695763]


In [63]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.83780818 0.82369361 0.72772627 0.59400802 0.88147226]


In [64]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

0.8814722586315198
0.025906094361890286


In [65]:
# split fractional and integral parts of a floating-point array

arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.46142723 0.6661179  0.32290803 0.5338844  0.92724537 0.37840597
 0.0058998  0.69306077 0.4681706  0.04749343]
integral:  [0. 6. 0. 0. 6. 6. 7. 9. 3. 2.]


In [66]:
# compute the overall mean
print(np.mean(arr))

0.47917979336472116


In [67]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.68129847 0.45054626 0.43782533 0.59320386 0.23302506]


In [68]:
# compute the overall median
print(np.median(arr))

0.4850245445453085


In [70]:
# Compute percentile
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.05277337 0.6932897  0.9688852 ]


In [71]:
# compute the overall standard deviation
print(np.std(arr))

0.26337010146868833


In [72]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.2043665  0.25256437 0.31673134 0.10325286 0.11536488]


In [73]:
# compute the overall variance
print(np.var(arr))

0.0693638103476272


#### compute the covariance & correlation

In [74]:
arr = np.random.rand(5,8)
print(np.cov(arr))

[[ 0.09576263  0.03659676  0.02442337 -0.03186927  0.06515226]
 [ 0.03659676  0.04883306  0.04568547 -0.03718539  0.02391727]
 [ 0.02442337  0.04568547  0.11132482  0.01105995  0.02761845]
 [-0.03186927 -0.03718539  0.01105995  0.08670134  0.00961384]
 [ 0.06515226  0.02391727  0.02761845  0.00961384  0.08053267]]


In [75]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.55733839]
 [-0.55733839  1.        ]]


In [76]:
# Element wise comparision

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [77]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


### select an element by row and column indices

In [78]:
arr = np.array(range(100)).reshape((10,10))

In [79]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


In [80]:
# indexing with slicing
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [81]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])    

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


#### find elements/indices by conditions


In [83]:
arr = np.arange(16).reshape(4,4)

# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [84]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


### Sorting

In [86]:
arr = np.random.rand(5,5)

In [87]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.50352663 0.03163959 0.18695805 0.28552798 0.17787025]
 [0.60808541 0.12278665 0.32552994 0.35674333 0.49172147]
 [0.6209603  0.35306748 0.89908311 0.56387144 0.51044588]
 [0.76069422 0.61451551 0.94274109 0.80676184 0.53978326]
 [0.82870399 0.73518102 0.97043612 0.9076692  0.76978951]]


In [88]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.50352663 0.03163959 0.18695805 0.28552798 0.17787025]
 [0.60808541 0.12278665 0.32552994 0.35674333 0.49172147]
 [0.6209603  0.35306748 0.89908311 0.56387144 0.51044588]
 [0.76069422 0.61451551 0.94274109 0.80676184 0.53978326]
 [0.82870399 0.73518102 0.97043612 0.9076692  0.76978951]]


In [89]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.03163959 0.17787025 0.18695805 0.28552798 0.50352663]
 [0.12278665 0.32552994 0.35674333 0.49172147 0.60808541]
 [0.35306748 0.51044588 0.56387144 0.6209603  0.89908311]
 [0.53978326 0.61451551 0.76069422 0.80676184 0.94274109]
 [0.73518102 0.76978951 0.82870399 0.9076692  0.97043612]]


#### Transpose

In [90]:
arr = np.random.rand(3,4)

In [91]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.45409362 0.15748832 0.78595016]
 [0.34069481 0.47518481 0.57901476]
 [0.9861522  0.6262122  0.2642017 ]
 [0.16895372 0.45060604 0.89100066]]
[[0.45409362 0.15748832 0.78595016]
 [0.34069481 0.47518481 0.57901476]
 [0.9861522  0.6262122  0.2642017 ]
 [0.16895372 0.45060604 0.89100066]]
[[0.45409362 0.15748832 0.78595016]
 [0.34069481 0.47518481 0.57901476]
 [0.9861522  0.6262122  0.2642017 ]
 [0.16895372 0.45060604 0.89100066]]


In [92]:
# transpose of a high dimensional array with specified order of axes

arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [93]:
arr

array([[0.45409362, 0.34069481, 0.9861522 , 0.16895372],
       [0.15748832, 0.47518481, 0.6262122 , 0.45060604],
       [0.78595016, 0.57901476, 0.2642017 , 0.89100066]])

In [95]:
arr.reshape((2,6))

array([[0.45409362, 0.34069481, 0.9861522 , 0.16895372, 0.15748832,
        0.47518481],
       [0.6262122 , 0.45060604, 0.78595016, 0.57901476, 0.2642017 ,
        0.89100066]])

In [96]:
# change the shape of an array in place
arr.resize((2,6))

In [97]:
arr

array([[0.45409362, 0.34069481, 0.9861522 , 0.16895372, 0.15748832,
        0.47518481],
       [0.6262122 , 0.45060604, 0.78595016, 0.57901476, 0.2642017 ,
        0.89100066]])

In [98]:
arr.flatten()

array([0.45409362, 0.34069481, 0.9861522 , 0.16895372, 0.15748832,
       0.47518481, 0.6262122 , 0.45060604, 0.78595016, 0.57901476,
       0.2642017 , 0.89100066])

In [101]:
# Append elements
arr = np.array([1,2,3])
arr = np.append(arr, 4) 
arr

array([1, 2, 3, 4])

In [104]:
arr1 = np.append(arr, [4,5,6]) 
arr1

array([1, 2, 3, 4, 4, 5, 6])

### Concatenate

In [105]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [106]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [107]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [108]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [111]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### Spliting Arrays

In [112]:
arr = np.random.rand(6,6)

In [113]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.35025428, 0.49333045, 0.76417099, 0.59152256, 0.94190507,
        0.66001557],
       [0.43294458, 0.75547266, 0.10286961, 0.20142897, 0.12820738,
        0.90939223],
       [0.88860486, 0.10936096, 0.08271586, 0.54153011, 0.92643415,
        0.6709928 ]]), array([[0.54491274, 0.60300492, 0.53152867, 0.68414853, 0.82608063,
        0.77705835],
       [0.66206893, 0.22194133, 0.18274774, 0.51741218, 0.05671366,
        0.52273918],
       [0.87825214, 0.81509821, 0.15399121, 0.81993871, 0.97879303,
        0.50041521]])]


In [115]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.35025428, 0.49333045, 0.76417099],
       [0.43294458, 0.75547266, 0.10286961],
       [0.88860486, 0.10936096, 0.08271586],
       [0.54491274, 0.60300492, 0.53152867],
       [0.66206893, 0.22194133, 0.18274774],
       [0.87825214, 0.81509821, 0.15399121]]), array([[0.59152256, 0.94190507, 0.66001557],
       [0.20142897, 0.12820738, 0.90939223],
       [0.54153011, 0.92643415, 0.6709928 ],
       [0.68414853, 0.82608063, 0.77705835],
       [0.51741218, 0.05671366, 0.52273918],
       [0.81993871, 0.97879303, 0.50041521]])]


### SET Operations

In [116]:
# Print unique elements
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [117]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


* compute the intersection & union of two arrays

In [118]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [120]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [121]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [122]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

In [123]:
# Matrix Multiplication

print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[2.32851159 2.09283397 2.71314372 2.05222656 1.98239006]
 [1.78116572 1.3473874  1.93066712 1.47239811 1.68722573]
 [2.01335003 1.34654977 2.30816337 1.37052623 1.83464873]
 [1.94317443 1.7085865  2.13800951 1.82595969 1.69654553]
 [0.70829553 0.72967854 1.12420694 0.76117313 0.69227336]]
[[2.32851159 2.09283397 2.71314372 2.05222656 1.98239006]
 [1.78116572 1.3473874  1.93066712 1.47239811 1.68722573]
 [2.01335003 1.34654977 2.30816337 1.37052623 1.83464873]
 [1.94317443 1.7085865  2.13800951 1.82595969 1.69654553]
 [0.70829553 0.72967854 1.12420694 0.76117313 0.69227336]]
[[2.32851159 2.09283397 2.71314372 2.05222656 1.98239006]
 [1.78116572 1.3473874  1.93066712 1.47239811 1.68722573]
 [2.01335003 1.34654977 2.30816337 1.37052623 1.83464873]
 [1.94317443 1.7085865  2.13800951 1.82595969 1.69654553]
 [0.70829553 0.72967854 1.12420694 0.76117313 0.69227336]]


In [124]:
# Compute Eigen values
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.48999615+0.j         -0.11885307+0.19747934j -0.11885307-0.19747934j
  0.58125628+0.17040057j  0.58125628-0.17040057j]


In [125]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[-3.35709832e-01  3.31667413e+00  2.76232607e+00  4.57987318e-02
  -5.51111747e+00]
 [-1.25107877e+00 -1.07909436e+00 -1.19129424e+00 -1.75231463e-01
   3.78351482e+00]
 [ 2.68832318e-01 -1.07620436e+00  1.46415118e-02 -1.00392647e+00
   1.90390324e+00]
 [ 3.44814037e-03 -1.11770731e+00 -8.20359825e-02  1.44014686e+00
   2.27367546e-01]
 [ 1.88496258e+00  1.30840048e+00 -5.88009105e-01 -6.86676910e-01
  -9.44404095e-01]]


In [126]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[-3.35709832e-01  3.31667413e+00  2.76232607e+00  4.57987318e-02
  -5.51111747e+00]
 [-1.25107877e+00 -1.07909436e+00 -1.19129424e+00 -1.75231463e-01
   3.78351482e+00]
 [ 2.68832318e-01 -1.07620436e+00  1.46415118e-02 -1.00392647e+00
   1.90390324e+00]
 [ 3.44814037e-03 -1.11770731e+00 -8.20359825e-02  1.44014686e+00
   2.27367546e-01]
 [ 1.88496258e+00  1.30840048e+00 -5.88009105e-01 -6.86676910e-01
  -9.44404095e-01]]


In [ ]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))